spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    minimumIdle: 5
    maximumPoolSize: 50
  jpa:
    properties:
      hibernate:
        show_sql: true

snowballs:
  server:
    port: 2600